package flag;
dialect  "mvel"

import ra.rta.models.*;
import java.util.GregorianCalendar
import java.util.Calendar;

// TODO: accumulate balances prior to balance

rule "negative savings balance"
    when
        $c: Customer($a : accounts)
//        $totalBalance : Number() from accumulate(Account(productType == "Deposit-Savings", $b: balance) from $a, sum($b))
        DepositAccount(type == "Deposit-Savings" && balance < 0) from $a
    then
        $c.addKPI(26426462);
end

rule "zero savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance == 0) from $a
    then
        $c.addKPI(2644264);
end

rule "lt 500 savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance > 0 && balance < 500) from $a
    then
        $c.addKPI(26462643);
end

rule "lt 1000 savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 500 && balance < 1000) from $a
    then
        $c.addKPI(2646232);
end

rule "lt 2500 savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 1000 && balance < 2500) from $a
    then
        $c.addKPI(63456365);
end

rule "lt 5000 savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 2500 && balance < 5000) from $a
    then
        $c.addKPI(62621626);
end

rule "lt 10k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 5000 && balance < 10000) from $a
    then
        $c.addKPI(264264562);
end

rule "lt 25k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 10000 && balance < 25000) from $a
    then
        $c.addKPI(246262);
end

rule "lt 50k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 25000 && balance < 50000) from $a
    then
        $c.addKPI(62765737);
end


rule "lt 100k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 50000 && balance < 100000) from $a
    then
        $c.addKPI(254754737);
end

rule "lt 250k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 100000 && balance < 250000) from $a
    then
        $c.addKPI(357473557);
end

rule "gt 250k savings balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && balance >= 250000) from $a
    then
        $c.addKPI(75473753);
end