package flag;
dialect  "mvel"

import ra.rta.models.*;
import java.util.GregorianCalendar
import java.util.Calendar;

rule "1 month savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths <= 1) from $a
    then
        $c.addKPI(4235125);
end

rule "2 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths == 2) from $a
    then
        $c.addKPI(143421);
end

rule "3 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths == 3) from $a
    then
        $c.addKPI(4134241);
end

rule "4 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths == 4) from $a
    then
        $c.addKPI(153512);
end

rule "6 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths > 4 && openDateMonths <= 6) from $a
    then
        $c.addKPI(153255);
end

rule "12 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths > 6 && openDateMonths <= 12) from $a
    then
        $c.addKPI(15325);
end

rule "24 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths > 12 && openDateMonths <= 24) from $a
    then
        $c.addKPI(1513213);
end

rule "36 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths > 24 && openDateMonths <= 36) from $a
    then
        $c.addKPI(15315315);
end

rule "More than 36 months savings recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Savings" && openDateMonths > 36) from $a
    then
        $c.addKPI(57566525);
end