package flag;
dialect  "mvel"

import ra.rta.models.*;
import java.util.GregorianCalendar
import java.util.Calendar;

rule "negative checking balance"
    when
        $c: Customer($a : accounts)
//        $totalBalance : Number() from accumulate(Account(productType == "Deposit-Checking", $b: balance) from $a, sum($b))
        DepositAccount(type == "Deposit-Checking" && balance < 0) from $a
    then
        $c.addKPI(5757545437);
end

rule "zero checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance == 0) from $a
    then
        $c.addKPI(7547537457);
end

rule "lt 500 checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance > 0 && balance < 500) from $a
    then
        $c.addKPI(3745735);
end

rule "lt 1000 checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 500 && balance < 1000) from $a
    then
        $c.addKPI(73454575);
end

rule "lt 2500 checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 1000 && balance < 2500) from $a
    then
        $c.addKPI(734573743);
end

rule "lt 5000 checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 2500 && balance < 5000) from $a
    then
        $c.addKPI(27475474537);
end

rule "lt 10k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 5000 && balance < 10000) from $a
    then
        $c.addKPI(75473753);
end

rule "lt 25k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 10000 && balance < 25000) from $a
    then
        $c.addKPI(6432624362);
end

rule "lt 50k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 25000 && balance < 50000) from $a
    then
        $c.addKPI(757543753);
end


rule "lt 100k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 50000 && balance < 100000) from $a
    then
        $c.addKPI(435364326);
end

rule "lt 250k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 100000 && balance < 250000) from $a
    then
        $c.addKPI(23474572);
end

rule "gt 250k checking balance"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && balance >= 250000) from $a
    then
        $c.addKPI(2725472376);
end