package flag;
dialect  "mvel"

import ra.rta.models.*;
import java.util.GregorianCalendar
import java.util.Calendar;

rule "1 product owned"
    when
        $c: Customer(accounts.size == 1)
    then
        $c.addKPI(62646264);
end

rule "2 products owned"
    when
        $c: Customer(accounts.size == 2)
    then
        $c.addKPI(2643662);
end

rule "3 products owned"
    when
        $c: Customer(accounts.size == 3)
    then
        $c.addKPI(26466242);
end

rule "4 products owned"
    when
        $c: Customer(accounts.size == 4)
    then
        $c.addKPI(264364264362);
end

rule "5 products owned"
    when
        $c: Customer(accounts.size == 5)
    then
        $c.addKPI(6426426426);
end

rule "6 products owned"
    when
        $c: Customer(accounts.size == 6)
    then
        $c.addKPI(26426426);
end

rule "7 products owned"
    when
        $c: Customer(accounts.size == 7)
    then
        $c.addKPI(656426426);
end

rule "8 products owned"
    when
        $c: Customer(accounts.size == 8)
    then
        $c.addKPI(46426264);
end

rule "9 products owned"
    when
        $c: Customer(accounts.size == 9)
    then
        $c.addKPI(1246426436);
end

rule "10 or more products owned"
    when
        $c: Customer(accounts.size >= 10)
    then
        $c.addKPI(6432462642);
end