package flag;
dialect  "mvel"

import ra.rta.models.*;
import java.util.GregorianCalendar
import java.util.Calendar;

rule "1 month checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths <= 1) from $a
    then
        $c.addKPI(64346234562);
end

rule "2 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths == 2) from $a
    then
        $c.addKPI(64643626);
end

rule "3 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths == 3) from $a
    then
        $c.addKPI(62436264);
end

rule "4 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths == 4) from $a
    then
        $c.addKPI(6234626);
end

rule "6 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths > 4 && openDateMonths <= 6) from $a
    then
        $c.addKPI(632642);
end

rule "12 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths > 6 && openDateMonths <= 12) from $a
    then
        $c.addKPI(26463);
end

rule "24 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths > 12 && openDateMonths <= 24) from $a
    then
        $c.addKPI(36236462);
end

rule "36 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths > 24 && openDateMonths <= 36) from $a
    then
        $c.addKPI(264632642);
end

rule "More than 36 months checking recency"
    when
        $c: Customer($a : accounts)
        DepositAccount(type == "Deposit-Checking" && openDateMonths > 36) from $a
    then
        $c.addKPI(262643264);
end