package flag;
dialect  "mvel"

import ra.rta.models.*;

/*
 * Doing a remove all here because there's no guarantee that the previous data is correct.
 * eg: yesterday someone is 17, but today they are 21 due to some error.
 * Without the remove all, they'd have the TEEN and YOUNG_ADULT KPIs.
 */
rule "child age"
    when
        $c: Customer(age >= 0 && age <= 12 && deceasedYear == 0)
    then
    	$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.CHILD);
end

rule "teen age"
    when
        $c: Customer(age >= 13 && age <= 17 && deceasedYear == 0)
    then
    	$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.TEEN);
end

rule "late teen age"
    when
        $c: Customer(age >= 18 && age <= 20 && deceasedYear == 0)
    then
    	$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.LATE_TEEN);
end

rule "young adult age"
    when
        $c: Customer(age >= 21 && age <= 24 && deceasedYear == 0)
    then
		$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.YOUNG_ADULT);
end

rule "adult age"
    when
        $c: Customer(age >= 25 && age <= 34 && deceasedYear == 0)
    then
    	$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.ADULT);
end

rule "family age"
    when
        $c: Customer(age >= 35 && age <= 44 && deceasedYear == 0)
    then
    	$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.FAMILY);
end

rule "midlife age"
    when
        $c: Customer(age >= 45 && age <= 54 && deceasedYear == 0)
    then
        $c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.MIDLIFE);
end

rule "empty nest age"
    when
        $c: Customer(age >= 55 && age <= 64 && deceasedYear == 0)
    then
        $c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.EMPTY_NEST);
end

rule "retirement age"
    when
        $c: Customer(age >= 65 && age <= 74 && deceasedYear == 0)
    then
        $c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.RETIREMENT);
end

rule "silver age"
    when
        $c: Customer(age >= 75 && age <= 200 && deceasedYear == 0)
    then
		$c.removeAllKPIs(AgeKPIs.ALL);
        $c.addKPI(AgeKPIs.SILVER);
end

rule "pining for the fjords"
	when
		$c: Customer(deceasedYear != 0)
	then
        $c.removeAllKPIs(AgeKPIs.ALL);
end
